# Generated by Django 2.2.6 on 2021-09-27 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670411, tzinfo=utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670490, tzinfo=utc))),
                ('delete_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670526, tzinfo=utc), null=True)),
                ('media_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(default='未命名素材', max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670411, tzinfo=utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670490, tzinfo=utc))),
                ('delete_time', models.DateTimeField(default=datetime.datetime(2021, 9, 27, 13, 37, 9, 670526, tzinfo=utc), null=True)),
                ('media_id', models.IntegerField(db_index=True)),
                ('content', models.TextField(null=True)),
                ('content_type', models.CharField(choices=[('algorithm_template', 'algorithm_template'), ('text', 'text')], default='text', max_length=200)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(default='一只猫咪不加糖', max_length=200)),
                ('title', models.CharField(max_length=500, null=True)),
                ('show_cover_pic', models.BooleanField(default=True)),
                ('digest', models.CharField(max_length=2000, null=True)),
                ('content_url', models.CharField(max_length=200, null=True)),
                ('source_url', models.CharField(max_length=200, null=True)),
                ('thumb_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_server.MediaModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
