# Generated by Django 2.2.16 on 2021-09-28 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_server', '0002_auto_20210927_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='content',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='media_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='media',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 11, 10, 7, 582314, tzinfo=utc)),
        ),
    ]
